name: Playwright Tests

on:
  push:
    branches:
      - develop

  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write


jobs:

  test:

    runs-on: ubuntu-latest


    steps:

      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4


      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm


      # Install Allure command line
      - name: Install Allure Commandline
        run: npm install -g allure-commandline


      # Install project dependencies
      - name: Install dependencies
        run: npm install


      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps


      # Execute tests
      - name: Run tests
        run: npm test
        continue-on-error: true


      # Generate Allure report
      - name: Generate Allure report
        run: npm run allure:generate


      # Upload report to GitHub Pages
      - name: Upload Allure Report
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report


      # Deploy report
      - name: Deploy Allure Report to GitHub Pages
        uses: actions/deploy-pages@v4